NHS Kiosk App: NHSKioskApp.Services.WebViewService Class Reference
NHSKioskApp.Services.WebViewService Class Reference
Service for managing the web viewer.
Public Member Functions
WebViewService ()
Constructs a WebViewService.
void UpdateBrowser (string url)
Sets the web view browser to a newly created browser starting at the specified url. Disposes the old browser, if it exists.
Static Public Member Functions
static bool IsNHSDomain (string url)
Checks if specified url exists in the NHS domain name space.
Properties
ChromiumWebBrowser Browser [get]
Property for _browser.
Events
Action? IsLoadingChanged
Action for when IsLoading has changed.
Events inherited from NHSKioskApp.Core.ObservableObject
PropertyChangedEventHandler? PropertyChanged
Additional Inherited Members
Protected Member Functions inherited from NHSKioskApp.Core.ObservableObject
virtual void OnPropertyChanged ([CallerMemberName] string? propertyName=null)
Detailed Description
Service for managing the web viewer.
Constructor & Destructor Documentation
WebViewService()
NHSKioskApp.Services.WebViewService.WebViewService ()
Constructs a WebViewService.
References NHSKioskApp.Services.WebViewService.UpdateBrowser().
Member Function Documentation
IsNHSDomain()
static bool NHSKioskApp.Services.WebViewService.IsNHSDomain (string url) static
Checks if specified url exists in the NHS domain name space.
Parameters
url URL to be checked
Returns
True if url is in NHS domain. Returns false otherwise.
Referenced by NHSKioskApp.Core.CefSharp.CustomRequestHandler.OnBeforeBrowse().
UpdateBrowser()
void NHSKioskApp.Services.WebViewService.UpdateBrowser (string url)
Sets the web view browser to a newly created browser starting at the specified url. Disposes the old browser, if it exists.
Parameters
url The starting url of the new browser.
References NHSKioskApp.Services.WebViewService.Browser.
Referenced by NHSKioskApp.Services.WebViewService.WebViewService().
Property Documentation
Browser
ChromiumWebBrowser NHSKioskApp.Services.WebViewService.Browser get
Property for _browser.
Referenced by NHSKioskApp.Services.WebViewService.UpdateBrowser().
Event Documentation
IsLoadingChanged
Action? NHSKioskApp.Services.WebViewService.IsLoadingChanged
Action for when IsLoading has changed.
The documentation for this class was generated from the following file:
C:/GitHub/Capstone-Team-3-NHS-Kiosk/NHSKioskApp/Services/WebViewService.cs