NHS Kiosk App: NHSKioskApp.App Class Reference
NHSKioskApp.App Class Reference
Class for the WPF App.
Public Member Functions
App ()
Constructor for the App. Sets up all services and view models through dependency injection.
void InitializeComponent ()
InitializeComponent.
void InitializeComponent ()
InitializeComponent.
Static Public Member Functions
static void Main ()
Application Entry Point.
static void Main ()
Application Entry Point.
Protected Member Functions
override void OnStartup (StartupEventArgs e)
Initializes the navigation service and main window for the app upon startup.
Detailed Description
Class for the WPF App.
App.
Constructor & Destructor Documentation
App()
NHSKioskApp.App.App ()
Constructor for the App. Sets up all services and view models through dependency injection.
Member Function Documentation
InitializeComponent() [1/2]
void NHSKioskApp.App.InitializeComponent ()
InitializeComponent.
Referenced by NHSKioskApp.App.Main().
InitializeComponent() [2/2]
void NHSKioskApp.App.InitializeComponent ()
InitializeComponent.
Main() [1/2]
static void NHSKioskApp.App.Main () static
Application Entry Point.
References NHSKioskApp.App.InitializeComponent().
Main() [2/2]
static void NHSKioskApp.App.Main () static
Application Entry Point.
References NHSKioskApp.App.InitializeComponent().
OnStartup()
override void NHSKioskApp.App.OnStartup (StartupEventArgs e) protected
Initializes the navigation service and main window for the app upon startup.
Parameters
e The startup event arguments.
The documentation for this class was generated from the following files:
C:/GitHub/Capstone-Team-3-NHS-Kiosk/NHSKioskApp/App.xaml.cs
C:/GitHub/Capstone-Team-3-NHS-Kiosk/NHSKioskApp/obj/x64/Release/net6.0-windows/App.g.cs
C:/GitHub/Capstone-Team-3-NHS-Kiosk/NHSKioskApp/obj/x64/Release/net6.0-windows/App.g.i.cs