NHS Kiosk App: NHSKioskApp.Services.QuizResultsService Class Reference
NHSKioskApp.Services.QuizResultsService Class Reference
Public Member Functions
QuizResultsService ()
bool IsInfoNeeded ()
int GetNumCorrect ()
void AddCorrect (Question q)
int GetNumWrong ()
string GetDisplayString ()
int GetNumQuestions ()
List< string > GetListToSend ()
void SetScore (Score score)
void AddToSend (string document)
void AddWrong (Question q)
List< Question > GetCorrect ()
List< Question > GetWrong ()
Score GetScore ()
void GenerateListToSend ()
Static Public Attributes
const string PhysicalCategory = "Physical Health"
const string MentalCategory = "Mental Health"
const string BehavioralCategory = "Behavorial"
const string TrainingCategory = "Training"
Properties
Score Score [get, set]
Events
Action ScoreChanged
Constructor & Destructor Documentation
QuizResultsService()
NHSKioskApp.Services.QuizResultsService.QuizResultsService ()
Member Function Documentation
AddCorrect()
void NHSKioskApp.Services.QuizResultsService.AddCorrect (Question q)
References NHSKioskApp.MVVM.Models.Score.Correct.
Referenced by NHSKioskApp.Services.QuizService.SelectAnswer().
AddToSend()
void NHSKioskApp.Services.QuizResultsService.AddToSend (string document)
References NHSKioskApp.MVVM.Models.Score.ListToSend.
Referenced by NHSKioskApp.Services.QuizResultsService.GenerateListToSend().
AddWrong()
void NHSKioskApp.Services.QuizResultsService.AddWrong (Question q)
References NHSKioskApp.MVVM.Models.Score.Behavioral, NHSKioskApp.Services.QuizResultsService.BehavioralCategory, NHSKioskApp.MVVM.Models.Question.Category, NHSKioskApp.Services.QuizResultsService.MentalCategory, NHSKioskApp.MVVM.Models.Score.MentalHealth, NHSKioskApp.Services.QuizResultsService.PhysicalCategory, NHSKioskApp.MVVM.Models.Score.PhysicalHealth, NHSKioskApp.MVVM.Models.Score.Training, NHSKioskApp.Services.QuizResultsService.TrainingCategory, and NHSKioskApp.MVVM.Models.Score.Wrong.
Referenced by NHSKioskApp.Services.QuizService.SelectAnswer().
GenerateListToSend()
void NHSKioskApp.Services.QuizResultsService.GenerateListToSend ()
References NHSKioskApp.Services.QuizResultsService.AddToSend(), NHSKioskApp.MVVM.Models.Score.Behavioral, NHSKioskApp.Services.QuizResultsService.BehavioralCategory, NHSKioskApp.MVVM.Models.Question.Category, NHSKioskApp.MVVM.Models.Question.Document, NHSKioskApp.Services.QuizResultsService.GetListToSend(), NHSKioskApp.Services.QuizResultsService.GetNumWrong(), NHSKioskApp.Services.QuizResultsService.GetWrong(), NHSKioskApp.MVVM.Models.Score.ListToSend, NHSKioskApp.Services.QuizResultsService.MentalCategory, NHSKioskApp.MVVM.Models.Score.MentalHealth, NHSKioskApp.Services.QuizResultsService.PhysicalCategory, NHSKioskApp.MVVM.Models.Score.PhysicalHealth, and NHSKioskApp.Services.QuizResultsService.TrainingCategory.
Referenced by NHSKioskApp.Services.QuizResultsService.GetScore().
GetCorrect()
List< Question > NHSKioskApp.Services.QuizResultsService.GetCorrect ()
References NHSKioskApp.MVVM.Models.Score.Correct.
GetDisplayString()
string NHSKioskApp.Services.QuizResultsService.GetDisplayString ()
References NHSKioskApp.Services.QuizResultsService.GetNumCorrect(), and NHSKioskApp.Services.QuizResultsService.GetNumQuestions().
GetListToSend()
List< string > NHSKioskApp.Services.QuizResultsService.GetListToSend ()
References NHSKioskApp.MVVM.Models.Score.ListToSend.
Referenced by NHSKioskApp.Services.QuizResultsService.GenerateListToSend().
GetNumCorrect()
int NHSKioskApp.Services.QuizResultsService.GetNumCorrect ()
References NHSKioskApp.MVVM.Models.Score.Correct.
Referenced by NHSKioskApp.Services.QuizResultsService.GetDisplayString(), NHSKioskApp.Services.QuizResultsService.GetNumQuestions(), and NHSKioskApp.Services.QuizResultsService.IsInfoNeeded().
GetNumQuestions()
int NHSKioskApp.Services.QuizResultsService.GetNumQuestions ()
References NHSKioskApp.Services.QuizResultsService.GetNumCorrect(), and NHSKioskApp.Services.QuizResultsService.GetNumWrong().
Referenced by NHSKioskApp.Services.QuizResultsService.GetDisplayString(), and NHSKioskApp.Services.QuizResultsService.IsInfoNeeded().
GetNumWrong()
int NHSKioskApp.Services.QuizResultsService.GetNumWrong ()
References NHSKioskApp.MVVM.Models.Score.Wrong.
Referenced by NHSKioskApp.Services.QuizResultsService.GenerateListToSend(), and NHSKioskApp.Services.QuizResultsService.GetNumQuestions().
GetScore()
Score NHSKioskApp.Services.QuizResultsService.GetScore ()
References NHSKioskApp.Services.QuizResultsService.GenerateListToSend(), and NHSKioskApp.Services.QuizResultsService.Score.
Referenced by NHSKioskApp.Services.QuizService.GetScore().
GetWrong()
List< Question > NHSKioskApp.Services.QuizResultsService.GetWrong ()
References NHSKioskApp.MVVM.Models.Score.Wrong.
Referenced by NHSKioskApp.Services.QuizResultsService.GenerateListToSend().
IsInfoNeeded()
bool NHSKioskApp.Services.QuizResultsService.IsInfoNeeded ()
References NHSKioskApp.Services.QuizResultsService.GetNumCorrect(), and NHSKioskApp.Services.QuizResultsService.GetNumQuestions().
SetScore()
void NHSKioskApp.Services.QuizResultsService.SetScore (Score score)
Member Data Documentation
BehavioralCategory
const string NHSKioskApp.Services.QuizResultsService.BehavioralCategory = "Behavorial" static
Referenced by NHSKioskApp.Services.QuizResultsService.AddWrong(), and NHSKioskApp.Services.QuizResultsService.GenerateListToSend().
MentalCategory
const string NHSKioskApp.Services.QuizResultsService.MentalCategory = "Mental Health" static
Referenced by NHSKioskApp.Services.QuizResultsService.AddWrong(), and NHSKioskApp.Services.QuizResultsService.GenerateListToSend().
PhysicalCategory
const string NHSKioskApp.Services.QuizResultsService.PhysicalCategory = "Physical Health" static
Referenced by NHSKioskApp.Services.QuizResultsService.AddWrong(), and NHSKioskApp.Services.QuizResultsService.GenerateListToSend().
TrainingCategory
const string NHSKioskApp.Services.QuizResultsService.TrainingCategory = "Training" static
Referenced by NHSKioskApp.Services.QuizResultsService.AddWrong(), and NHSKioskApp.Services.QuizResultsService.GenerateListToSend().
Property Documentation
Score
Score NHSKioskApp.Services.QuizResultsService.Score get set
Referenced by NHSKioskApp.Services.QuizResultsService.GetScore().
Event Documentation
ScoreChanged
Action NHSKioskApp.Services.QuizResultsService.ScoreChanged
The documentation for this class was generated from the following file:
C:/GitHub/CSCI4950/Capstone-Team-3-NHS-Kiosk/NHSKioskApp/NHSKioskApp/Services/QuizResultsService.cs