NHS Kiosk App: NHSKioskApp.Services.QuizService Class Reference
NHSKioskApp.Services.QuizService Class Reference
Public Member Functions
QuizService (IDatabaseService database, QuizResultsService results)
Question GetCurrentQuestion ()
int GetCorrectAnswerIndex ()
void SelectAnswer (int answer)
void NextQuestion ()
bool IsEndOfQuiz ()
void HideAnswers ()
void UpdateAnswer (int index, string bordercolor, string fontcolor, string bkgroundcolor, string visibility="Visible")
Score GetScore ()
void StartQuiz (string animalType)
Properties
Quiz CurrentQuiz [get, set]
int CurrentQuestionIndex [get, set]
bool Answered [get, set]
Events
Action CurrentQuestionChanged
Action AnswerChanged
Constructor & Destructor Documentation
QuizService()
NHSKioskApp.Services.QuizService.QuizService (IDatabaseService database, QuizResultsService results)
Member Function Documentation
GetCorrectAnswerIndex()
int NHSKioskApp.Services.QuizService.GetCorrectAnswerIndex ()
References NHSKioskApp.MVVM.Models.Question.Answers, and NHSKioskApp.Services.QuizService.GetCurrentQuestion().
Referenced by NHSKioskApp.Services.QuizService.SelectAnswer().
GetCurrentQuestion()
Question NHSKioskApp.Services.QuizService.GetCurrentQuestion ()
References NHSKioskApp.Services.QuizService.CurrentQuestionIndex, NHSKioskApp.Services.QuizService.CurrentQuiz, and NHSKioskApp.MVVM.Models.Quiz.Questions.
Referenced by NHSKioskApp.Services.QuizService.GetCorrectAnswerIndex(), NHSKioskApp.Services.QuizService.HideAnswers(), NHSKioskApp.Services.QuizService.SelectAnswer(), and NHSKioskApp.Services.QuizService.UpdateAnswer().
GetScore()
Score NHSKioskApp.Services.QuizService.GetScore ()
References NHSKioskApp.Services.QuizResultsService.GetScore().
HideAnswers()
void NHSKioskApp.Services.QuizService.HideAnswers ()
References NHSKioskApp.MVVM.Models.Question.Answers, NHSKioskApp.Services.QuizService.GetCurrentQuestion(), and NHSKioskApp.Services.QuizService.UpdateAnswer().
Referenced by NHSKioskApp.Services.QuizService.SelectAnswer().
IsEndOfQuiz()
bool NHSKioskApp.Services.QuizService.IsEndOfQuiz ()
References NHSKioskApp.Services.QuizService.CurrentQuestionIndex.
NextQuestion()
void NHSKioskApp.Services.QuizService.NextQuestion ()
References NHSKioskApp.Services.QuizService.Answered, and NHSKioskApp.Services.QuizService.CurrentQuestionIndex.
SelectAnswer()
void NHSKioskApp.Services.QuizService.SelectAnswer (int answer)
References NHSKioskApp.Services.QuizResultsService.AddCorrect(), NHSKioskApp.Services.QuizResultsService.AddWrong(), NHSKioskApp.Services.QuizService.Answered, NHSKioskApp.Services.QuizService.GetCorrectAnswerIndex(), NHSKioskApp.Services.QuizService.GetCurrentQuestion(), NHSKioskApp.Services.QuizService.HideAnswers(), NHSKioskApp.MVVM.Models.Question.NextButtonVisibility, and NHSKioskApp.Services.QuizService.UpdateAnswer().
StartQuiz()
void NHSKioskApp.Services.QuizService.StartQuiz (string animalType)
References NHSKioskApp.Services.QuizService.Answered, NHSKioskApp.Services.Interfaces.IDatabaseService.CreateQuiz(), NHSKioskApp.Services.QuizService.CurrentQuestionIndex, and NHSKioskApp.Services.QuizService.CurrentQuiz.
Referenced by NHSKioskApp.MVVM.ViewModels.QuizSelectViewModel.QuizSelectViewModel().
UpdateAnswer()
void NHSKioskApp.Services.QuizService.UpdateAnswer (int index, string bordercolor, string fontcolor, string bkgroundcolor, string visibility = "Visible")
References NHSKioskApp.MVVM.Models.Question.Answers, NHSKioskApp.MVVM.Models.Answer.BackgroundColor, NHSKioskApp.MVVM.Models.Answer.BorderColor, NHSKioskApp.MVVM.Models.Answer.FontColor, NHSKioskApp.Services.QuizService.GetCurrentQuestion(), and NHSKioskApp.MVVM.Models.Answer.Visibility.
Referenced by NHSKioskApp.Services.QuizService.HideAnswers(), and NHSKioskApp.Services.QuizService.SelectAnswer().
Property Documentation
Answered
bool NHSKioskApp.Services.QuizService.Answered get set
Referenced by NHSKioskApp.Services.QuizService.NextQuestion(), NHSKioskApp.Services.QuizService.SelectAnswer(), and NHSKioskApp.Services.QuizService.StartQuiz().
CurrentQuestionIndex
int NHSKioskApp.Services.QuizService.CurrentQuestionIndex get set
Referenced by NHSKioskApp.Services.QuizService.GetCurrentQuestion(), NHSKioskApp.Services.QuizService.IsEndOfQuiz(), NHSKioskApp.Services.QuizService.NextQuestion(), and NHSKioskApp.Services.QuizService.StartQuiz().
CurrentQuiz
Quiz NHSKioskApp.Services.QuizService.CurrentQuiz get set
Referenced by NHSKioskApp.Services.QuizService.GetCurrentQuestion(), and NHSKioskApp.Services.QuizService.StartQuiz().
Event Documentation
AnswerChanged
Action NHSKioskApp.Services.QuizService.AnswerChanged
CurrentQuestionChanged
Action NHSKioskApp.Services.QuizService.CurrentQuestionChanged
The documentation for this class was generated from the following file:
C:/GitHub/CSCI4950/Capstone-Team-3-NHS-Kiosk/NHSKioskApp/NHSKioskApp/Services/QuizService.cs